/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabiles_lspunavigation;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Amazing
 */
public class FrmCCS_Cabiles_CCS extends javax.swing.JFrame {

    /**
     * Creates new form FrmCCS_Cabiles_CCS
     */
    public FrmCCS_Cabiles_CCS() {
        // remove the default minimize and close buttons
        setUndecorated(true);
        
        initComponents();
        
        // set window to fullscreen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        
        // set window to center screen
        setLocationRelativeTo(null);

        if (ThemeManager.themeApplied) {
            applyTheme();
        }
        
        setVisible(true);
    }
    public void applyTheme() {
        // change theme code
        mainFrame.setBackground(ThemeManager.backgroundColor);
        headerPanel.setBackground(ThemeManager.headerColor);
        footerPanel.setBackground(ThemeManager.footerColor);

        lblTitle1.setForeground(ThemeManager.labelColor);
        lblTitle2.setForeground(ThemeManager.labelColor);

        lbl1.setForeground(ThemeManager.labelColor);
        lbl2.setForeground(ThemeManager.labelColor);
        lbl3.setForeground(ThemeManager.labelColor);
        lbl4.setForeground(ThemeManager.labelColor);
        lbl5.setForeground(ThemeManager.labelColor);
        lbl6.setForeground(ThemeManager.labelColor);
        lbl7.setForeground(ThemeManager.labelColor);
        lbl8.setForeground(ThemeManager.labelColor);
        lbl9.setForeground(ThemeManager.labelColor);
        lbl10.setForeground(ThemeManager.labelColor);

        lbl1.setBackground(ThemeManager.backgroundColor);
        lbl2.setBackground(ThemeManager.backgroundColor);
        lbl3.setBackground(ThemeManager.backgroundColor);
        lbl4.setBackground(ThemeManager.backgroundColor);
        lbl5.setBackground(ThemeManager.backgroundColor);
        lbl6.setBackground(ThemeManager.backgroundColor);
        lbl7.setBackground(ThemeManager.backgroundColor);
        lbl8.setBackground(ThemeManager.backgroundColor);
        lbl9.setBackground(ThemeManager.backgroundColor);
        lbl10.setBackground(ThemeManager.backgroundColor);

        lbl11.setBackground(ThemeManager.headerColor);
        lbl12.setBackground(ThemeManager.headerColor);
        postGradPanel.setBackground(ThemeManager.headerColor);
    }

    public void goBackToMainMenu() {
        // hide current department frame
        this.setVisible(false);   
        // show existing main frame
        FrmMainMenu_CABILES.instance.setVisible(true);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        btnMinimize1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        btnBackToHome = new javax.swing.JButton();
        btnGoToCOE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl1 = new java.awt.Label();
        lbl3 = new java.awt.Label();
        lbl4 = new java.awt.Label();
        lbl5 = new java.awt.Label();
        lbl10 = new java.awt.Label();
        lbl2 = new java.awt.Label();
        lbl9 = new java.awt.Label();
        lbl8 = new java.awt.Label();
        lbl7 = new java.awt.Label();
        lbl6 = new java.awt.Label();
        postGradPanel = new javax.swing.JPanel();
        lbl11 = new java.awt.Label();
        lbl12 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1565, 1286));

        mainFrame.setBackground(new java.awt.Color(255, 153, 51));

        headerPanel.setBackground(new java.awt.Color(0, 0, 102));

        lblTitle1.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("College of Computer Studies");

        btnMinimize1.setBackground(new java.awt.Color(255, 255, 102));
        btnMinimize1.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        btnMinimize1.setText("-");
        btnMinimize1.setBorder(null);
        btnMinimize1.setBorderPainted(false);
        btnMinimize1.setFocusPainted(false);
        btnMinimize1.setOpaque(true);
        btnMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimize1MouseExited(evt);
            }
        });
        btnMinimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimize1ActionPerformed(evt);
            }
        });

        btnClose1.setBackground(new java.awt.Color(255, 0, 0));
        btnClose1.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 255, 255));
        btnClose1.setText("X");
        btnClose1.setBorder(null);
        btnClose1.setBorderPainted(false);
        btnClose1.setFocusPainted(false);
        btnClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClose1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClose1MouseExited(evt);
            }
        });
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 682, Short.MAX_VALUE)
                .addComponent(btnMinimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinimize1)
                    .addComponent(btnClose1))
                .addContainerGap())
        );

        footerPanel.setBackground(new java.awt.Color(0, 0, 102));

        lblTitle2.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("College of Computer Studies");

        btnBackToHome.setBackground(new java.awt.Color(255, 255, 102));
        btnBackToHome.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        btnBackToHome.setText("Go Back to Home");
        btnBackToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackToHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackToHomeMouseExited(evt);
            }
        });
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });

        btnGoToCOE.setBackground(new java.awt.Color(0, 153, 0));
        btnGoToCOE.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        btnGoToCOE.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToCOE.setText("Back (COE)");
        btnGoToCOE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGoToCOEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGoToCOEMouseExited(evt);
            }
        });
        btnGoToCOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToCOEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnGoToCOE, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footerPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitle2))
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGoToCOE, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabiles_lspunavigation/CCS_PIC.png"))); // NOI18N

        lbl1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("It is the department for aspiring web and software developers,");

        lbl3.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Programs Offered in College of Computer Studies");

        lbl4.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("> Bachelor of Science in Information Technology");

        lbl5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("Major/s available on Third Year Standing: \n");

        lbl10.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 255, 255));
        lbl10.setText("Intelligent Systems, and Graphics and Visualization\n");

        lbl2.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText(" animators and AI engineers.");

        lbl9.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl9.setForeground(new java.awt.Color(255, 255, 255));
        lbl9.setText("Major/s available on Third Year Standing: \n");

        lbl8.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("> Bachelor of Science in Computer Science");

        lbl7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 255, 255));
        lbl7.setText("and Web and Mobile Application Development");

        lbl6.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("Animation and Motion Graphics, Service Management Program,");

        postGradPanel.setBackground(new java.awt.Color(0, 0, 102));

        lbl11.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lbl11.setForeground(new java.awt.Color(255, 255, 255));
        lbl11.setText("Post Gradute Program\n");

        lbl12.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lbl12.setForeground(new java.awt.Color(255, 255, 255));
        lbl12.setText("Master in Information Technology");

        javax.swing.GroupLayout postGradPanelLayout = new javax.swing.GroupLayout(postGradPanel);
        postGradPanel.setLayout(postGradPanelLayout);
        postGradPanelLayout.setHorizontalGroup(
            postGradPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postGradPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(postGradPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        postGradPanelLayout.setVerticalGroup(
            postGradPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postGradPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postGradPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postGradPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 1545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseEntered
        btnMinimize1.setForeground(Color.BLACK);
        btnMinimize1.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnMinimize1MouseEntered

    private void btnMinimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize1MouseExited
        btnMinimize1.setForeground(Color.BLACK);
        btnMinimize1.setBackground(new java.awt.Color(255,255,102));
    }//GEN-LAST:event_btnMinimize1MouseExited

    private void btnMinimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimize1ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimize1ActionPerformed

    private void btnClose1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose1MouseEntered
        btnClose1.setForeground(Color.BLACK);
        btnClose1.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnClose1MouseEntered

    private void btnClose1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose1MouseExited
        btnClose1.setForeground(Color.WHITE);
        btnClose1.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_btnClose1MouseExited

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnBackToHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToHomeMouseEntered
        btnBackToHome.setForeground(Color.WHITE);
        btnBackToHome.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnBackToHomeMouseEntered

    private void btnBackToHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToHomeMouseExited
        btnBackToHome.setForeground(Color.BLACK);
        btnBackToHome.setBackground(new java.awt.Color(255,255,102));
    }//GEN-LAST:event_btnBackToHomeMouseExited

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        goBackToMainMenu();
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnGoToCOEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoToCOEMouseEntered
        btnGoToCOE.setForeground(Color.WHITE);
        btnGoToCOE.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnGoToCOEMouseEntered

    private void btnGoToCOEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoToCOEMouseExited
        btnGoToCOE.setForeground(Color.WHITE);
        btnGoToCOE.setBackground(new java.awt.Color(0,153,0));
    }//GEN-LAST:event_btnGoToCOEMouseExited

    private void btnGoToCOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToCOEActionPerformed
        // show the COE frame
        FrmCCS_CABILES_COE frame = new FrmCCS_CABILES_COE();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnGoToCOEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCCS_Cabiles_CCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCCS_Cabiles_CCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCCS_Cabiles_CCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCCS_Cabiles_CCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCCS_Cabiles_CCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnGoToCOE;
    private javax.swing.JButton btnMinimize1;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label lbl1;
    private java.awt.Label lbl10;
    private java.awt.Label lbl11;
    private java.awt.Label lbl12;
    private java.awt.Label lbl2;
    private java.awt.Label lbl3;
    private java.awt.Label lbl4;
    private java.awt.Label lbl5;
    private java.awt.Label lbl6;
    private java.awt.Label lbl7;
    private java.awt.Label lbl8;
    private java.awt.Label lbl9;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel postGradPanel;
    // End of variables declaration//GEN-END:variables
}
