/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabiles_lspunavigation;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Amazing
 */
public class FrmMainMenu_CABILES extends javax.swing.JFrame {
    // static reference for back home button
    public static FrmMainMenu_CABILES instance;  
    
    /**
     * Creates new form FrmMainMenu_CABILES
     */
    public FrmMainMenu_CABILES() {
        // store the instance to keep styling instead of reverting 
        instance = this; 

        // remove the default minimize and close buttons
        setUndecorated(true);
        
        initComponents();    
        
        // set window to fullscreen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        
        // set window to center screen
        setLocationRelativeTo(null);
        
        // set button colors because it looks gray by default
        btnCTE.setBackground(Color.WHITE);
        btnCBAA.setBackground(Color.WHITE);
        btnCIT.setBackground(Color.WHITE);
        btnCOE.setBackground(Color.WHITE);
        btnCCS.setBackground(Color.WHITE);
        btnChangeTheme.setBackground(Color.WHITE);
        btnRevertOrig.setBackground(Color.WHITE);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        footerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCTE = new javax.swing.JButton();
        lblCTE = new javax.swing.JLabel();
        btnCBAA = new javax.swing.JButton();
        lblCBAA1 = new javax.swing.JLabel();
        btnCIT = new javax.swing.JButton();
        lblCIT = new javax.swing.JLabel();
        lblCBAA2 = new javax.swing.JLabel();
        btnCOE = new javax.swing.JButton();
        lblCOE = new javax.swing.JLabel();
        btnCCS = new javax.swing.JButton();
        lblCCS = new javax.swing.JLabel();
        btnChangeTheme = new javax.swing.JButton();
        btnRevertOrig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setBackground(new java.awt.Color(153, 153, 255));

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOME COLLEGES IN LSPU - Cabiles");

        btnMinimize.setBackground(new java.awt.Color(255, 255, 102));
        btnMinimize.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        btnMinimize.setText("-");
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setFocusPainted(false);
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setFocusPainted(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnMinimize)
                    .addComponent(btnClose))
                .addGap(36, 36, 36))
        );

        footerPanel.setBackground(new java.awt.Color(0, 0, 0));
        footerPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Amazing Grace O. Cabiles and 3IS2");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        btnCTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabiles_lspunavigation/LOGO_CTE.png"))); // NOI18N
        btnCTE.setBorder(null);
        btnCTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCTEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCTEMouseExited(evt);
            }
        });
        btnCTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTEActionPerformed(evt);
            }
        });

        lblCTE.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblCTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCTE.setText("College of Teacher Education");

        btnCBAA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabiles_lspunavigation/LOGO_CBAA.png"))); // NOI18N
        btnCBAA.setBorder(null);
        btnCBAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCBAAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCBAAMouseExited(evt);
            }
        });
        btnCBAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBAAActionPerformed(evt);
            }
        });

        lblCBAA1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblCBAA1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCBAA1.setText("College of Business,");

        btnCIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabiles_lspunavigation/LOGO_CIT.png"))); // NOI18N
        btnCIT.setBorder(null);
        btnCIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCITMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCITMouseExited(evt);
            }
        });
        btnCIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCITActionPerformed(evt);
            }
        });

        lblCIT.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblCIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCIT.setText("College of Industrial Technology");

        lblCBAA2.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblCBAA2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCBAA2.setText(" Administration  and Accountancy");

        btnCOE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabiles_lspunavigation/LOGO_COE.png"))); // NOI18N
        btnCOE.setBorder(null);
        btnCOE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCOEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCOEMouseExited(evt);
            }
        });
        btnCOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOEActionPerformed(evt);
            }
        });

        lblCOE.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblCOE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCOE.setText("College of Engineering");

        btnCCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabiles_lspunavigation/LOGO_CCS.png"))); // NOI18N
        btnCCS.setBorder(null);
        btnCCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCCSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCCSMouseExited(evt);
            }
        });
        btnCCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCSActionPerformed(evt);
            }
        });

        lblCCS.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        lblCCS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCCS.setText("College of Computer Studies");

        btnChangeTheme.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnChangeTheme.setText("Change Theme");
        btnChangeTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangeThemeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangeThemeMouseExited(evt);
            }
        });
        btnChangeTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeThemeActionPerformed(evt);
            }
        });

        btnRevertOrig.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        btnRevertOrig.setText("Revert to Original");
        btnRevertOrig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevertOrigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevertOrigMouseExited(evt);
            }
        });
        btnRevertOrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevertOrigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCBAA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCTE, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCTE, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblCBAA1))
                            .addComponent(lblCBAA2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCIT, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCIT, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCOE, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(btnCCS, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCOE, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCCS, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addComponent(btnChangeTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRevertOrig, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblCTE))
                            .addComponent(btnCTE, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblCBAA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCBAA2))
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCBAA, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCCS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCOE, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainFrameLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblCOE)))
                        .addGap(91, 91, 91)
                        .addComponent(lblCCS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                        .addComponent(btnCIT, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                        .addComponent(lblCIT)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangeTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRevertOrig, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)))
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTEActionPerformed
        // show the CTE frame
        FrmCCS_CABILES_CTE frame = new FrmCCS_CABILES_CTE();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCTEActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setForeground(Color.BLACK);
        btnClose.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setForeground(Color.WHITE);
        btnClose.setBackground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setForeground(Color.BLACK);
        btnMinimize.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setForeground(Color.BLACK);
        btnMinimize.setBackground(new java.awt.Color(255,255,102));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnCTEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCTEMouseEntered
        btnCTE.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCTEMouseEntered

    private void btnCTEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCTEMouseExited
        btnCTE.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCTEMouseExited

    private void btnCBAAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCBAAMouseEntered
        btnCBAA.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCBAAMouseEntered

    private void btnCBAAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCBAAMouseExited
        btnCBAA.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCBAAMouseExited

    private void btnCITMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCITMouseEntered
        btnCIT.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCITMouseEntered

    private void btnCITMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCITMouseExited
        btnCIT.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCITMouseExited

    private void btnCOEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCOEMouseEntered
        btnCOE.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCOEMouseEntered

    private void btnCOEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCOEMouseExited
        btnCOE.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCOEMouseExited

    private void btnCCSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCCSMouseExited
        btnCCS.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCCSMouseExited

    private void btnCCSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCCSMouseEntered
        btnCCS.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCCSMouseEntered

    private void btnCBAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBAAActionPerformed
        // show the CBAA frame
        FrmCCS_CABILES_CBAA frame = new FrmCCS_CABILES_CBAA();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCBAAActionPerformed

    private void btnCITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCITActionPerformed
        // show the CIT frame
        FrmCCS_CABILES_CIT frame = new FrmCCS_CABILES_CIT();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCITActionPerformed

    private void btnCOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOEActionPerformed
        // show the COE frame
        FrmCCS_CABILES_COE frame = new FrmCCS_CABILES_COE();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCOEActionPerformed

    private void btnCCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCSActionPerformed
        // show the CCS frame
        FrmCCS_Cabiles_CCS frame = new FrmCCS_Cabiles_CCS();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCCSActionPerformed
    
    private void btnChangeThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeThemeActionPerformed
        ThemeManager.nextTheme();

        // apply the theme to current frame
        mainFrame.setBackground(ThemeManager.backgroundColor);
        headerPanel.setBackground(ThemeManager.headerColor);
        footerPanel.setBackground(ThemeManager.footerColor);

        // change colors of the label
        lblCTE.setForeground(ThemeManager.labelColor);
        lblCBAA1.setForeground(ThemeManager.labelColor);
        lblCBAA2.setForeground(ThemeManager.labelColor);
        lblCIT.setForeground(ThemeManager.labelColor);
        lblCOE.setForeground(ThemeManager.labelColor);
        lblCCS.setForeground(ThemeManager.labelColor);
        
        ThemeManager.themeApplied = true;        
    }//GEN-LAST:event_btnChangeThemeActionPerformed

    private void btnChangeThemeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeThemeMouseEntered
        btnChangeTheme.setForeground(Color.WHITE);
        btnChangeTheme.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnChangeThemeMouseEntered

    private void btnChangeThemeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeThemeMouseExited
        btnChangeTheme.setForeground(Color.BLACK);
        btnChangeTheme.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnChangeThemeMouseExited

    private void btnRevertOrigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevertOrigMouseEntered
        btnRevertOrig.setForeground(Color.WHITE);
        btnRevertOrig.setBackground(Color.BLACK);    }//GEN-LAST:event_btnRevertOrigMouseEntered

    private void btnRevertOrigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevertOrigMouseExited
        btnRevertOrig.setForeground(Color.BLACK);
        btnRevertOrig.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnRevertOrigMouseExited

    // Reference frames
    private FrmCCS_CABILES_CTE cteFrame;
    private FrmCCS_CABILES_CBAA cbaaFrame;
    private FrmCCS_CABILES_CIT citFrame;
    private FrmCCS_CABILES_COE coeFrame;
    private FrmCCS_Cabiles_CCS ccsFrame;
    
    private void btnRevertOrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevertOrigActionPerformed
        ThemeManager.themeApplied = false;
        
        // main Frame
        mainFrame.setBackground(new Color(153,153,255));
        headerPanel.setBackground(Color.BLACK);
        footerPanel.setBackground(Color.BLACK);

        // Change colors of the label
        lblCTE.setForeground(Color.BLACK);
        lblCBAA1.setForeground(Color.BLACK);
        lblCBAA2.setForeground(Color.BLACK);
        lblCIT.setForeground(Color.BLACK);
        lblCOE.setForeground(Color.BLACK);
        lblCCS.setForeground(Color.BLACK);
        
        // other frames
        if (cteFrame != null && cteFrame.isVisible()) {
            cteFrame.dispose();                 // close the frame
            cteFrame = new FrmCCS_CABILES_CTE(); // reopen with default styling
        }
        
        if (cbaaFrame != null && cbaaFrame.isVisible()) {
            cbaaFrame.dispose();
            cbaaFrame = new FrmCCS_CABILES_CBAA();
        }
        
        if (citFrame != null && citFrame.isVisible()) {
            citFrame.dispose();
            citFrame = new FrmCCS_CABILES_CIT();
        }
        
        if (coeFrame != null && coeFrame.isVisible()) {
            coeFrame.dispose();
            coeFrame = new FrmCCS_CABILES_COE();
        }

        if (ccsFrame != null && ccsFrame.isVisible()) {
            ccsFrame.dispose();
            ccsFrame = new FrmCCS_Cabiles_CCS();
        }
    }//GEN-LAST:event_btnRevertOrigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu_CABILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu_CABILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu_CABILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu_CABILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainMenu_CABILES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCBAA;
    private javax.swing.JButton btnCCS;
    private javax.swing.JButton btnCIT;
    private javax.swing.JButton btnCOE;
    private javax.swing.JButton btnCTE;
    private javax.swing.JButton btnChangeTheme;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnRevertOrig;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCBAA1;
    private javax.swing.JLabel lblCBAA2;
    private javax.swing.JLabel lblCCS;
    private javax.swing.JLabel lblCIT;
    private javax.swing.JLabel lblCOE;
    private javax.swing.JLabel lblCTE;
    private javax.swing.JPanel mainFrame;
    // End of variables declaration//GEN-END:variables
}